os: linux
dist: xenial
sudo: required
language: cpp

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Y2zv9t+958KfOm6gtN5D70clBeSsCDwzNGV++RBMl7i3Ck50++Ur5Ssluzj4D7T2vruye+gfE8MILRT5ix8MvTwp/xTyzfUocGj56MnlYQRJmvkrHgf5iDF7tZJf8FMJfAlORt8rn27rHXNNcHrKi5CPGwGGAMxgC4BEcaxmiIR2BT7epdkl14c+jpds80JChK1fehmQ3aVrluydyAMODX8lj7azb0SsxueVJZ9MugYd8UpCib6kSYo1J63+dvYwmbqmOUuhSDDBb3fvcnnP3Nf5ZIk/4sR0PBNpsLZdbwulTSSKrcouxKlBGYAlpCFhGQ537eu3n7YN03jge0ouoZzMTsmcH9afpquuIojsrVlumNJUq+Zl85xMg/tliYJ4Hl8fUGHDLUel3TigiiIcveFvDHdT+UsjfJ2YsvChwbNtqBmYufdfYUg7wZwKP7dNjp12z/QGp7hhLeEJdxi/flZBmStd2xsRRmQMd3pJUBcO36tCEpGckXWREDccJREEo/mPjHHzZ0rtFX0TRStIyKcvFKTlLrEtAZdMgFSxXajv8oRQAdqfU+1/4WizS5jpIuSTEt0AV7xeBIOMhKnhX2p6mJ5aGI3dleBD05LryKwJPIgVTZPSNYi3xPlxhohZHrbIkDOeNXz2cbFYtwCvgpZ+E44V9cdFlml7BXOx9ss="
  - BUILD_TARGET=linux 
  - GEN_BINDING_AND_COCOSFILE=true

before_install:
  - tools/travis-scripts/before-install.sh
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "JohnCoconut/cocos2d-x"
      description: "cocos2d-x coverity scan"
    notification_email: mywtfmp3@gmail.com
    build_command_prepend: "mkdir build/cmake-build; cd build/cmake-build; cmake -GNinja ../.."
    build_command: "ninja"
    branch_pattern: coverity-scan

cache:
  bundler: true

notifications:
  email: false
